package com.bridgeit.FunctionalPrograms;

import java.util.ArrayList;
/******************************************************************************
 *  Compilation:  javac -CouponNumbers.java
 *  Execution:    java - com.bridgeit.AlgorithmPrograms.CouponNumbers
 *  
 *  Purpose: Print the output Coupon numbers  
 *
 *  @author  Srujan Madipeddi
 *  @version 1.0
 *  @Date   12-03-2019
 *
 ******************************************************************************/
import java.util.InputMismatchException;

import com.bridgeit.utilitypack.Utility;

public class CouponNumbers {
	public static void main(String[] args) {
		try {
			System.out.println("Enter numbers how many coupons you need ");
			// Taking input from user
			int number = Utility.getInteger();
			ArrayList<Integer> coupan = new ArrayList<Integer>();
			for (int i = 1; i <= number; i++) {
				int generating = Utility.getRandomInt();
				// Used contains method for removing duplicate
				// Generated by getRandomInt method
				if (coupan.contains(generating)) {
					i--;
				} else {
					// Adding coupons into array list
					coupan.add(generating);
				}
			}
			for (int coupans : coupan) {
				// Printing coupons on console
				System.out.println("Coupons are " + coupans);
			}
		}
		// Catching the exception
		catch (InputMismatchException e) {
			System.err.println("Please enter numbers only");
		}

	}

}
